# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='lang',
            field=models.CharField(default='English', help_text="Enter a the book's natural language (e.g. English, French, Japanese etc.)", max_length=50),
            preserve_default=False,
        ),
    ]
