# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20171118_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_modify_book', 'Create, modify, or delete books'),)},
        ),
    ]
